### ISSUE TITLE
[Bug] Crash when SearchAPI response has an empty array

### ISSUE THREAD

**Issue by aghilas-xb** [woosmap/woosmap-geofencing-android-sdk#28]
Hello !

The steps that make it crash for me:
1. WoosmapSettings.visitEnable = true, WoosmapSettings.searchAPIEnable = true
2. Initial lat/lng location: [48.949592, 2.512897]
3. Change location (I use the google emulator) to [48.909895, 2.422258]

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.webgeoservices.woosmapgeofencing.PositionsManager$requestSearchAPI$req$1$1.run(PositionsManager.kt:253)
```

A more detailed stackTrace:
```
2021-04-07 08:50:41.532 D/WoosmapSdk: Location[fused 48,949592,2,512897 hAcc=20 et=+11h39m54s983ms alt=0.0 vel=0.0 bear=90.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
2021-04-07 08:50:41.535 D/WoosmapVisit: Location[fused 48,949592,2,512897 hAcc=20 et=+11h39m54s983ms alt=0.0 vel=0.0 bear=90.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
2021-04-07 08:50:41.546 D/WoosmapVisit: distance : 0.0
2021-04-07 08:50:41.553 D/WoosmapVisit: get New Location
2021-04-07 08:50:41.554 D/WoosmapVisit: Always Static
2021-04-07 08:50:46.547 D/WoosmapSdk: Location[fused 48,909895,2,422258 hAcc=20 et=+11h39m59s996ms alt=0.0 vel=0.0 bear=90.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
2021-04-07 08:50:46.548 D/WoosmapVisit: Location[fused 48,909895,2,422258 hAcc=20 et=+11h39m59s996ms alt=0.0 vel=0.0 bear=90.0 vAcc=40 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
2021-04-07 08:50:46.553 D/WoosmapVisit: distance : 7974.849
2021-04-07 08:50:46.576 D/WoosmapVisit: get New Location
2021-04-07 08:50:46.577 D/WoosmapVisit: Not static Anyway
2021-04-07 08:50:46.794 E/AndroidRuntime: FATAL EXCEPTION: Thread-24
    Process: *****
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.webgeoservices.woosmapgeofencing.PositionsManager$requestSearchAPI$req$1$1.run(PositionsManager.kt:253)
        at java.lang.Thread.run(Thread.java:919)
```

SearchApi response:
```
{"type": "FeatureCollection", "features": [], "pagination": {"page": 1, "pageCount": 1}}
```

Thank you !

**Comment by Llumbroso** [comment]
resolve in version 1.0.2
