### ISSUE TITLE
[BUG] Crash due to missing overload on LocationUpdatesService enableLocationBackground on earlier Android API

### ISSUE THREAD

**Issue by soulcramer** [woosmap/woosmap-geofencing-android-sdk#31]
Hello !

We have repeated crashes reported by one of our tester using a device on Android 8 I suppose it's caused by the usage of a method added in a API.

The steps that make it crash for me:
I can't yet reproduce it yet in my app but we can see from the stackTrace that this line in https://github.com/woosmap/woosmap-geofencing-android-sdk/blob/3ffb2da0199c3db6e675fbd1d73a7908c862c0ee/woosmapgeofencing/src/main/java/com/webgeoservices/woosmapgeofencing/LocationUpdatesService.java#L191

is calling [startForeground(int id, Notification notification, int foregroundServiceType)](https://developer.android.com/reference/android/app/Service.html#startForeground(int,%20android.app.Notification,%20int)) which was added in API 29. A fix would be, I suppose, to use the overload method [startForeground(int id, Notification notification)](https://developer.android.com/reference/android/app/Service.html#startForeground(int,%20android.app.Notification)) when the device api is < API 29.

I'm trying to set up a device < API29 to reproduce it, I'll follow up if I succeed.

A more detailed stackTrace:
Android API 26 on a Samsung Galaxy S7
```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method startForeground(ILandroid/app/Notification;I)V in class Landroid/app/Service; or its super classes (declaration of 'android.app.Service' appears in /system/framework/framework.jar)
       at com.webgeoservices.woosmapgeofencing.LocationUpdatesService.enableLocationBackground(LocationUpdatesService.java:191)
       at com.webgeoservices.woosmapgeofencing.Woosmap$2.onServiceConnected(Woosmap.java:450)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1658)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1687)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```
Thank you !

**Comment by Llumbroso** [comment]
fix in version 1.0.7
